### ISSUE TITLE
Client Rewrite

### ISSUE THREAD

**Issue by ghost** [yamamushi/theasciiproject#23]
Client needs to be rewritten to handle depreceated features from libtcod.

**Comment by yamamushi** [comment]
Need to throw out libtcod and replace the client with a pure SDL client.
- Cleaner Interface
- Using Serialization instead of TPL
- Resizable Windows
- Sound(?)
- Etc.

The idea is to revamp the interface to a more user-friendly format, as the one I put together really only served my specific testing needs.

**Comment by yamamushi** [comment]
Resizable Windows -> Done
Sound -> Done / Implemented

Cleaner Interface -> In Progress
Cleaner Code -> In Progress
Widgets Collection -> In Progress
